# Generated by Django 4.2.7 on 2023-12-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
