# Generated by Django 4.2.7 on 2023-12-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('M', 'MENS DRESS'), ('W', 'WOMEN DRESS'), ('K', 'KIDS'), ('S', 'SPORTS'), ('H', 'SHOES'), ('P', 'PERFUME'), ('C', 'COSMETIC ITEMS'), ('B', 'BEAUTY ITEMS'), ('a', 'all items')], default='l', max_length=100),
        ),
    ]
