# Generated by Django 4.2.7 on 2023-12-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('M', 'MENS '), ('W', 'WOMENs'), ('K', 'KIDS'), ('S', 'SPORTS DRESS'), ('H', 'SHOES'), ('B', 'BEAUTY ITEMS'), ('a', 'all items')], default='l', max_length=100),
        ),
    ]
