# Generated by Django 4.2.7 on 2023-12-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_products_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
