# Generated by Django 4.2.7 on 2023-12-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_mycart_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
