# Generated by Django 4.2.7 on 2024-01-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mycart',
        ),
    ]
